# Generated by Django 5.0.14 on 2025-10-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testregistration',
            table='app_testregistration',
        ),
    ]
