# Generated by Django 5.0.14 on 2025-10-07 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_questionpaper_is_public_and_more'),
        ('user_tests', '0002_alter_testregistration_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='app.question')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='user_tests.testregistration')),
            ],
            options={
                'unique_together': {('registration', 'question')},
            },
        ),
    ]
