# Generated by Django 5.0.14 on 2025-12-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0003_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
