# Generated by Django 5.0.14 on 2025-12-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0004_userresponse_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='testregistration',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
