# Generated by Django 5.0.14 on 2025-12-04 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_tests', '0006_testregistration_is_shortlisted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GD', 'Group Discussion'), ('TECH', 'Technical Interview'), ('HR', 'HR Round'), ('FINAL', 'Final Selection')], max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateStageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('HOLD', 'On Hold')], default='PENDING', max_length=10)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('feedback_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(blank=True, help_text='The user who evaluated this stage.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(help_text="Candidate's Test Registration record.", on_delete=django.db.models.deletion.CASCADE, related_name='stage_statuses', to='user_tests.testregistration')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_candidates', to='recruitment.recruitmentstage')),
            ],
            options={
                'ordering': ['stage__order', 'updated_at'],
                'unique_together': {('registration', 'stage')},
            },
        ),
    ]
