# Generated by Django 5.0.14 on 2025-12-04 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_questionpaper_is_private_link_active_and_more'),
        ('recruitment', '0001_initial'),
        ('user_tests', '0006_testregistration_is_shortlisted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Archived', 'Archived')], default='Open', max_length=50)),
                ('public_link_slug', models.SlugField(help_text='Unique URL identifier', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='app.questionpaper')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.CharField(choices=[('Applied', 'Applied'), ('Written Test Passed', 'Written Test Passed'), ('GD Round', 'Group Discussion Round'), ('Interview Round', 'Technical Interview'), ('HR Round', 'HR Interview'), ('Final Offer', 'Final Offer'), ('Rejected', 'Rejected')], default='Applied', max_length=50)),
                ('is_hired', models.BooleanField(default=False)),
                ('test_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to='user_tests.testregistration')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='RoundFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=50)),
                ('score', models.IntegerField(blank=True, help_text='Score out of 10', null=True)),
                ('comments', models.TextField()),
                ('recommendation', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Hold', 'Hold')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='recruitment.candidate')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('candidate', 'round_name', 'interviewer')},
            },
        ),
        migrations.DeleteModel(
            name='CandidateStageStatus',
        ),
        migrations.DeleteModel(
            name='RecruitmentStage',
        ),
    ]
