# Generated by Django 5.0.14 on 2025-12-04 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_questionpaper_is_private_link_active_and_more'),
        ('recruitment', '0002_jobpost_candidate_roundfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Application End Date'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience_max',
            field=models.IntegerField(default=5, verbose_name='Experience Max (Years)'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience_min',
            field=models.IntegerField(default=0, verbose_name='Experience Min (Years)'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full-Time', max_length=50, verbose_name='Job Type'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Job Location'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='pay_scale',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pay Scale / Salary Range'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='positions_available',
            field=models.IntegerField(default=1, verbose_name='Positions Available'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills_required',
            field=models.TextField(blank=True, verbose_name='Skills Required (Comma separated)'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='total_rounds',
            field=models.IntegerField(default=3, verbose_name='Total Interview Rounds'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='question_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='app.questionpaper', verbose_name='Written Test Question Paper'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Job Title'),
        ),
    ]
