# Generated by Django 5.0.14 on 2025-12-08 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_candidate_cover_letter_candidate_current_ctc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('round_type', models.CharField(choices=[('Applied', 'Applied'), ('Written Test Passed', 'Written Test Passed'), ('GD Round', 'Group Discussion Round'), ('Interview Round', 'Technical Interview'), ('HR Round', 'HR Interview'), ('Final Offer', 'Final Offer'), ('Rejected', 'Rejected')], max_length=50, verbose_name='Applicable Round')),
                ('cutoff_score', models.IntegerField(default=60, help_text='Minimum score required to pass')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('round_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Parameter Name')),
                ('weight', models.IntegerField(default=10, help_text='Max score for this parameter')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='recruitment.evaluationtemplate')),
            ],
        ),
    ]
