# Generated by Django 5.0.14 on 2025-12-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_evaluationtemplate_evaluationparameter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluationtemplate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='evaluationtemplate',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Template Name'),
        ),
        migrations.RemoveField(
            model_name='evaluationtemplate',
            name='round_type',
        ),
    ]
