# Generated by Django 5.0.14 on 2025-12-08 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_alter_evaluationtemplate_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Round Name')),
                ('round_type', models.CharField(choices=[('Applied', 'Applied'), ('Written Test Passed', 'Written Test Passed'), ('GD Round', 'Group Discussion Round'), ('Interview Round', 'Technical Interview'), ('HR Round', 'HR Interview'), ('Final Offer', 'Final Offer'), ('Rejected', 'Rejected')], max_length=50, verbose_name='Round Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluation_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_rounds', to='recruitment.evaluationtemplate', verbose_name='Linked Evaluation Template')),
            ],
        ),
    ]
