# Generated by Django 5.0.14 on 2025-12-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_roundmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=1, help_text='Order of the round (1, 2, 3...)')),
                ('evaluation_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.evaluationtemplate', verbose_name='Evaluation Template')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='recruitment.jobpost')),
                ('round_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.roundmaster', verbose_name='Round Name')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
