# Generated by Django 5.0.14 on 2025-12-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_jobround'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobRound',
        ),
    ]
