# Generated by Django 5.0.14 on 2025-12-08 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_delete_jobround'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='recruitment.jobpost')),
                ('round_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.roundmaster', verbose_name='Round Type')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
