# Generated by Django 5.0.14 on 2025-10-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_papersection_section_skill_question_questionpaper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
