# Generated by Django 5.0.14 on 2025-10-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_questionpaper_total_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpaper",
            name="is_public_active",
            field=models.BooleanField(
                default=True,
                help_text="Controls if the public sharing link is currently active.",
            ),
        ),
    ]
