# Generated by Django 5.0.14 on 2025-10-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_questionpaper_is_public_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpaper",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Overall status of the paper. If inactive, it cannot be taken.",
            ),
        ),
    ]
