# Generated by Django 5.0.14 on 2025-10-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_questionpaper_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
