# Generated by Django 5.0.14 on 2025-10-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_skill_options_skill_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
