# Generated by Django 5.0.14 on 2025-10-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_questionpaper_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='is_public',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='is_public_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
