# Generated by Django 5.0.14 on 2025-10-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_questionpaper_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SA', 'Short Answer'), ('TF', 'True/False'), ('CODE', 'Coding'), ('DESC', 'Descriptive'), ('UN', 'Unclassified')], default='UN', max_length=4),
        ),
    ]
