# Generated by Django 5.0.14 on 2025-10-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'app_testregistration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
            ],
            options={
                'db_table': 'user_tests_userresponse',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SA', 'Short Answer'), ('CODE', 'Coding')], max_length=15),
        ),
    ]
