# Generated by Django 5.0.14 on 2025-10-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_testregistration_userresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='cutoff_score',
            field=models.PositiveIntegerField(default=70, help_text='Minimum percentage to pass (e.g., 70)'),
        ),
    ]
