# Generated by Django 5.0.14 on 2025-11-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_questionpaper_cutoff_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='cutoff_score',
            field=models.PositiveIntegerField(default=20, help_text='Minimum percentage to pass (e.g., 70)'),
        ),
    ]
