# Generated by Django 5.0.14 on 2025-11-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_questionpaper_cutoff_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='is_private_link_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
