# Generated by Django 5.0.14 on 2025-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_questionpaper_is_private_link_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersection',
            name='weightage',
            field=models.PositiveIntegerField(default=0, help_text='Weightage in percentage for this section'),
        ),
    ]
