# """
# Django settings for ai_test project. <-- FIX: 'project_name' को 'ai_test' से बदला गया।

# Generated by 'django-admin startproject' using Django 5.2.6.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path
# import os
# import environ

# # Render database connection ke liye import karein
# import dj_database_url  # <-- ADDED

# # Static files ko efficiently serve karne ke liye yeh use hota hai (whitenoise install karna hoga)
# import sys

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-rf^i_@h*%*-6bz7n5djy8d2r26z+e!y-s4=h2g83pv=uptw)gk"

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True  # Production mein False rakhein

# # Render aur custom domain hosts ko allow karein
# ALLOWED_HOSTS = [
#     ".onrender.com",
#     "ai-test.onrender.com",
#     "127.0.0.1",
#     "127.0.0.1:8000",
# ]  # <-- UPDATED


# # Application definition

# INSTALLED_APPS = [
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     "app",
#     "user_tests",
#     "widget_tweaks",
# ]

# MIDDLEWARE = [
#     # WhiteNoise middleware ko security middleware ke theek neeche add karein (whitenoise install zaroori hai)
#     "django.middleware.security.SecurityMiddleware",
#     "whitenoise.middleware.WhiteNoiseMiddleware",  # <-- ADDED (After installing 'whitenoise')
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]

# ROOT_URLCONF = "ai_test.urls"

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [os.path.join(BASE_DIR, "templates")],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.debug",
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]
# WSGI_APPLICATION = "ai_test.wsgi.application"
# # --- ADD YOUR EMAIL SETTING HERE ---

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "shweta.ladne.averybit@gmail.com"
# EMAIL_HOST_PASSWORD = "qwgh jagp euzh qcwi"


# # ----------------------------------------------------------------------
# #                         DATABASE CONFIGURATION
# # ----------------------------------------------------------------------

# # Render environment variable 'DATABASE_URL' ka upyog karein
# DATABASES = {
#     "default": dj_database_url.config(
#         # DATABASE_URL environment variable se connect karein
#         default=os.environ.get("DATABASE_URL"),
#         conn_max_age=600,
#         conn_health_checks=True,
#     )
# }

# # Agar environment variable set nahi hai (jaise ki local development mein), to SQLite use karein
# # Agar aap local dev mein bhi PostgreSQL use karna chahte hain, to is section ko comment kar dein
# if not os.environ.get("DATABASE_URL"):
#     print("Using SQLite for local development.")
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.sqlite3",
#             "NAME": BASE_DIR / "db.sqlite3",
#         }
#     }

# # ----------------------------------------------------------------------
# # ----------------------------------------------------------------------


# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
#     },
# ]

# # ----------------------------------------------------------------------
# #                         GEMINI API KEY CONFIGURATION (Hardcoded for testing)
# # ----------------------------------------------------------------------
# # WARNING: Yeh key production code mein nahi honi chahiye.
# # TESTING ke liye, aap apni key ko single quotes mein yahan daal sakte hain.

# GEMINI_API_KEY = "AIzaSyDB23HkzpmpWCy-9pv4zmowqg-gKd1DShw"  # <-- YAHAN APNI KEY DAALEN


# # Old environ configuration remove kar di gayi hai.
# # env = environ.Env(...)
# # environ.Env.read_env(...)
# # ----------------------------------------------------------------------


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

# USE_I18N = True

# USE_TZ = True


# # ----------------------------------------------------------------------
# #                         STATIC FILES CONFIGURATION
# # ----------------------------------------------------------------------

# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = "static/"

# # Production mein static files ko collect karne ki jagah
# STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # <-- ADDED

# # Local static files directories
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),
# ]

# # ----------------------------------------------------------------------
# # ----------------------------------------------------------------------


# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
"""
Django settings for project_name project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os  # Yeh line file ke top par add karein agar nahi hai
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'  

# इमेज सेव होने की जगह (सिस्टम के लिए)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-rf^i_@h*%*-6bz7n5djy8d2r26z+e!y-s4=h2g83pv=uptw)gk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app",
    "user_tests",
    "widget_tweaks",
    'recruitment',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ai_test.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],  # Yeh line add karein
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
WSGI_APPLICATION = "ai_test.wsgi.application"
# --- ADD YOUR EMAIL SETTING HERE ---

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "shweta.ladne.averybit@gmail.com"
EMAIL_HOST_PASSWORD = "qwgh jagp euzh qcwi"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "Recruitment",
        "USER": "postgres",
        "PASSWORD": "12345",
        "HOST": "localhost",
        "PORT": "5432",
    }
}
ALLOWED_HOSTS = ["127.0.0.1", "localhost", "192.168.1.10", "10.0.0.42"]
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

env = environ.Env(
    # Set casting default for API key (e.g., read as a string)
    GEMINI_API_KEY=(str, ""),
    OPENAI_API_KEY=(str, "")
)
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# settings.py
GEMINI_API_KEY = env("GEMINI_API_KEY")
OPENAI_API_KEY = env("OPENAI_API_KEY")
print(f"DEBUG: OpenAI Key Loaded: {'Yes' if OPENAI_API_KEY else 'No'}") # DO NOT PRINT THE ACTUAL KEY FOR SECURITY
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Django ko batayein ki global static folder kahan hai
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
